remove gulp
akashic-games/akashic-cli-update pull request #7
Opened 2018-12-12 10:50 UTC by ShinobuTakahashi

掲題の通り。

- gulpを削除し、gulpに関連するモジュールを削除。
- npm scriptの修正

2018-12-12 11:01 UTC, xnv requested changes

2018-12-12 11:01 UTC, xnv commented on package.json
> +	"test:compile": "tsc -p ./spec",
インデントがずれています。

2018-12-12 11:08 UTC, ShinobuTakahashi commented on package.json
> +	"test:compile": "tsc -p ./spec",
インデント修正しました

2018-12-13 11:00 UTC, xnv approved these changes

2018-12-13 11:04 UTC, merged